<?php

/**
 * @file Installation hooks
 * @author "NextPay.ir" <info@nextpay.ir>
 * 
 * @see http://www.nextpay.ir
 * 
 * Copyright 2015-2016 - nextpay.ir - All rights reserved.
 * For Licence, see README.txt and README.fa.txt
 */

/**
 * Implements hook_install().
 */
function uc_nextpay_install() {
  
}

/**
 * Implements hook_uninstall().
 */
function uc_nextpay_uninstall() {
  variable_del('uc_nextpay_ApiKey');
  variable_del('uc_nextpay_soapmode');
}
